### ISSUE TITLE
Dear Dev. Can you add Opera support

### ISSUE THREAD

**Issue by wjk199511140034** [willscott/ChromeProxy#6]
that was awesome addon, I love it switch direct/proxy in one single click, but it's can t work in Opera, which also use Chrome kit

**Comment by willscott** [comment]
If opera uses the same API, i'm not sure what would fail here, since this is a pretty standard use of the `crome.proxy` extension API.  If you have a specific thing you need changed, I can do that. I don't have opera though.

**Comment by wjk199511140034** [comment]
Oh,sad but its ok, I found other addon in Opera store
Thank U,anyway

2017-05-21 23:34 GMT+08:00 Will <notifications@github.com>:
